config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :memberships
  resources :clients
  resources :gyms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :gyms, through: :memberships
    has_many :memberships, dependent: :destroy
    accepts_nested_attributes_for :memberships

    validates :name, presence: true
    validates :age, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 18, message: '-> Must be older than 18 to sign up'}

    scope :client_memberships, -> {Client.joins(:memberships)}

end

app/models/gym.rb
class Gym < ApplicationRecord
    has_many :clients, through: :memberships
    has_many :memberships, dependent: :destroy
    accepts_nested_attributes_for :memberships
    validates :name, presence: true
    validates :address, presence: true

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :client
  belongs_to :gym
  accepts_nested_attributes_for :gym
  accepts_nested_attributes_for :client
  
  validates :charge, presence: true, numericality: {only_integer: true}
  validates_associated :gym
  validates_associated :client

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: %i[ show edit update destroy ]

  # GET /gyms or /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1 or /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms or /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to gym_url(@gym), notice: "Gym was successfully created." }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1 or /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to gym_url(@gym), notice: "Gym was successfully updated." }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1 or /gyms/1.json
  def destroy
    @gym.destroy

    respond_to do |format|
      format.html { redirect_to gyms_url, notice: "Gym was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gym_params
      params.require(:gym).permit(:name, :address)
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[ show edit update destroy ]
  before_action :new_gym_client, only: [ :create ]
  before_action :set_form_variables, only: [ :new ]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new

  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    respond_to do |format|
        if new_gym_client && @membership.save
          format.html { redirect_to membership_url(@membership), notice: "Membership was successfully created." }
          format.json { render :show, status: :created, location: @membership }
        elsif !new_gym_client
          set_form_variables
          format.html { redirect_to new_membership_url, notice: "Cannot sign up to the same gym twice!" }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        else
          set_form_variables
          format.html { redirect_to new_membership_url, status: :unprocessable_entity }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end 

      end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url, notice: "Membership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_gym_client
    Membership.where(gym_id: params[:membership][:gym_id]).where(client_id: params[:membership][:client_id]).count == 0 ? true : false 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
         
    def set_form_variables
      @clients = Client.all
      @gyms = Gym.all
    end 

    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.require(:membership).permit(:charge, :client_id, :gym_id)
    end

   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= client.age %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/gyms/_form.html.erb
<%= form_with(model: gym) do |form| %>
  <% if gym.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
        <% gym.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gyms/_gym.html.erb
<div id="<%= dom_id gym %>">
  <p>
    <strong>Name:</strong>
    <%= gym.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= gym.address %>
  </p>

</div>

app/views/gyms/edit.html.erb
<h1>Editing gym</h1>

<%= render "form", gym: @gym %>

<br>

<div>
  <%= link_to "Show this gym", @gym %> |
  <%= link_to "Back to gyms", gyms_path %>
</div>

app/views/gyms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gyms</h1>

<div id="gyms">
  <% @gyms.each do |gym| %>
    <%= render gym %>
    <p>
      <%= link_to "Show this gym", gym %>
    </p>
  <% end %>
</div>

<%= link_to "New gym", new_gym_path %>

app/views/gyms/new.html.erb
<h1>New gym</h1>

<%= render "form", gym: @gym %>

<br>

<div>
  <%= link_to "Back to gyms", gyms_path %>
</div>

app/views/gyms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gym %>

<div>
  <%= link_to "Edit this gym", edit_gym_path(@gym) %> |
  <%= link_to "Back to gyms", gyms_path %>

  <%= button_to "Destroy this gym", @gym, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gymapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
    <%= yield %>
    <%= render 'shared/nav' %>
  </body>
</html>

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :charge, style: "display: block" %>
    <%= form.select :charge, [40,60,80].map {|t| t}, class: "form-select" %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id, @clients.map {|c| [c.name, c.age, c.id] }, class: "form-select" %>
  </div>

  <div>
    <%= form.label :gym_id, style: "display: block" %>
    <%= form.select :gym_id, @gyms.map {|c| [c.name, c.address, c.id] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Charge:</strong>
    <%= membership.charge %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= membership.client_id %>
  </p>

  <p>
    <strong>Gym:</strong>
    <%= membership.gym_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Welcome!</h1>
<h2>What would you like to do?</h2>

<ul>
<li><%= link_to 'View gyms', gyms_path %></li>
<li><%= link_to 'View clients', clients_path %></li>
<li><%= link_to 'Add a membership', new_membership_path %></li>
<li><%= link_to 'Delete a membership', memberships_path %></li>
</ul>

app/views/shared/_nav.html.erb
<div><%= link_to 'Home', root_path %></div>